/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#2c303d",
        "surface-container-high": "#1c2b3c",
        "surface": "#051424",
        "tertiary-fixed-dim": "#c3c6d7",
        "on-secondary-container": "#b0b2ff",
        "surface-container-low": "#0d1c2d",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#002118",
        "on-primary": "#00382b",
        "inverse-primary": "#006b55",
        "on-surface-variant": "#bacac2",
        "secondary": "#c0c1ff",
        "inverse-surface": "#d4e4fa",
        "on-error": "#690005",
        "tertiary": "#d4d7e8",
        "surface-dim": "#051424",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#010f1f",
        "surface-container": "#122131",
        "secondary-container": "#3131c0",
        "on-tertiary-container": "#474b59",
        "surface-bright": "#2c3a4c",
        "secondary-fixed": "#e1e0ff",
        "on-background": "#d4e4fa",
        "on-surface": "#d4e4fa",
        "on-tertiary-fixed-variant": "#434654",
        "on-tertiary-fixed": "#171b28",
        "primary": "#46f1c5",
        "on-secondary": "#1000a9",
        "surface-variant": "#273647",
        "tertiary-container": "#b8bbcc",
        "surface-container-highest": "#273647",
        "primary-container": "#00d4aa",
        "on-primary-fixed-variant": "#00513f",
        "surface-tint": "#28dfb5",
        "on-secondary-fixed": "#07006c",
        "primary-fixed": "#55fcd0",
        "outline": "#85948d",
        "on-primary-container": "#005643",
        "background": "#051424",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "outline-variant": "#3b4a44",
        "error-container": "#93000a",
        "primary-fixed-dim": "#28dfb5",
        "tertiary-fixed": "#dfe2f3",
        "inverse-on-surface": "#233143",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "section-gap": "120px",
        "container": "1200px",
        "container-max": "1200px",
        "stack-lg": "32px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body": ["Inter", "system-ui", "sans-serif"],
        "headline": ["Space Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "card-title": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container": "1200px",
      },
      animation: {
        "fade-up": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-up-delay-1": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.1s forwards",
        "fade-up-delay-2": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.2s forwards",
        "fade-up-delay-3": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.3s forwards",
        "fade-up-delay-4": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.4s forwards",
        "fade-in": "fadeIn 0.4s ease-out forwards",
        "scale-in": "scaleIn 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-in-right": "slideInRight 0.3s ease-out forwards",
        "slide-out-right": "slideOutRight 0.3s ease-in forwards",
        "pulse-dot": "pulseDot 2s ease-in-out infinite",
        "count-up": "countUp 2s ease-out forwards",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideInRight: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        slideOutRight: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(100%)" },
        },
        pulseDot: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(70, 241, 197, 0.4)" },
          "50%": { boxShadow: "0 0 0 12px rgba(70, 241, 197, 0)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
